
version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table witch contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primarykey for the listing
        tests:
          - unique
          - not_null
      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed_minimum_nights") }}'
        tests:
          - positiv_value

  - name: dim_hosts_cleansed
    description: Cleansed table witch contains Airbnb hosts.
    columns:
      - name: host_id
        description: '{{ doc("host_id") }}'
        tests:
          - unique
          - not_null
      - name: host_name
        description: '{{ doc("host_name") }}'
        tests:
          - not_null
      - name: is_superhost
        description: '{{ doc("superhost") }}'
        tests:
          - accepted_values:
              values: ['f','t']

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listing')
    columns: 
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn